name: CI

on:
  push:
    branches:
      - b-ci
  pull_request:
    branches:
      - master
      - develop

env:
  CLAZY_CHECKS: "level1"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        container-image:
          - "registry.opensuse.org/opensuse/tumbleweed"
          - "registry.suse.com/bci/bci-base:15.4"
        compiler:
          - gcc
        pam:
          - ON
    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container-image }}

    steps:
      - name: Dependencies (zypper)
        if: contains(matrix.container-image, 'suse')
        run: |
          zypper --non-interactive in git-core gcc-c++ cmake make pam-devel pkgconfig "pkgconfig(libsystemd)" "pkgconfig(xcb-xkb)" "pkgconfig(Qt5Quick)" "pkgconfig(Qt5Test)" extra-cmake-modules
      - uses: actions/checkout@v3
      - name: Dependencies (dnf)
        if: ${{ contains(matrix.container-image, 'fedora') || contains(matrix.container-image, 'centos') }}
        run: |
          set -x
          dnf --assumeyes install dnf-plugins-core
          if [ -f /etc/centos-release ]; then dnf --assumeyes config-manager --set-enabled crb && dnf --assumeyes install epel-release; fi
          dnf --assumeyes builddep sddm
          dnf --assumeyes install clang clazy
      - name: Dependencies (deb-type)
        if: ${{ contains(matrix.container-image, 'ubuntu') }}
        run: |
          set -x
          sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
          apt-get update -y
          DEBIAN_FRONTEND=noninteractive apt-get build-dep sddm -y
          DEBIAN_FRONTEND=noninteractive apt-get install clang clazy qml-module-qttest -y
      - name: Build
        run: |
          set -x
          mkdir -p build
          cd build
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            #export CXX=clang++
            export CXX=clazy
          fi
          cmake .. \
            -DBUILD_MAN_PAGES:BOOL=ON \
            -DENABLE_PAM:BOOL=${{ matrix.pam }}
          make -j $(getconf _NPROCESSORS_ONLN)
          make install
      - name: Test
        env:
          CTEST_OUTPUT_ON_FAILURE: "1"
        working-directory: build
        run: make test
